# Generated by Django 3.2.13 on 2022-06-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BugApp', '0003_auto_20220613_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avote',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answerid', to='BugApp.answers'),
        ),
        migrations.AlterField(
            model_name='avote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userid2', to=settings.AUTH_USER_MODEL),
        ),
    ]
