# Generated by Django 3.2.13 on 2022-06-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BugApp', '0004_auto_20220613_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qvote',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questionid', to='BugApp.questions'),
        ),
        migrations.AlterField(
            model_name='qvote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL),
        ),
    ]
