# Generated by Django 3.2.13 on 2022-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugApp', '0005_auto_20220613_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='questions',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
