# Generated by Django 3.2.13 on 2022-06-14 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BugApp', '0006_auto_20220614_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='thumbs',
            field=models.ManyToManyField(blank=True, default=None, related_name='thumbs', to=settings.AUTH_USER_MODEL),
        ),
    ]
