# Generated by Django 3.2.13 on 2022-06-15 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BugApp', '0008_auto_20220614_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 15, 7, 58, 28, 358863, tzinfo=utc))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionviews', to='BugApp.questions')),
            ],
        ),
    ]
