# Generated by Django 3.2.13 on 2022-06-17 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BugApp', '0009_questionview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 32, 51, 524691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='questionview',
            name='session',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
