# Generated by Django 3.2.13 on 2022-06-20 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BugApp', '0010_auto_20220617_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 8, 14, 30, 790448, tzinfo=utc)),
        ),
    ]
